name: Deploy to DirectAdmin via FTP

on:
  push:
    branches:
      - main  # Chạy khi có code mới push vào nhánh main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files to Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Đường dẫn trên host DirectAdmin (xem ảnh bạn gửi thì nó là public_html)
        server-dir: ./domains/hoangquocdat.id.vn/public_html/
        # Chỉ upload những file cần thiết, loại bỏ file git
        exclude: |
          **/.git*
          **/.github*
